import './globals.css'
import Nav from './nav'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='mx-10'>
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  )
}
